# Site settings
title: Yangyang Fu
email: yangyang.fu@tamu.edu
url: https://example.github.io
description: "I'm a PhD in Architectural Engineering, motivated by the idea of autonomous and intelligent buildings and cities. Always enthusiastic about innovative techniques and ideas. Also always looking for inner peace."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: active learning to get rid of the old me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009690854711
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/YangyangFu
  - title: linkedin
    url: https://www.linkedin.com/in/yangyangfu

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman